const router = require('express').Router();

// router.use('/users', require('./users'));  // /api/users/...
router.use('/plans', require('./plans'));  // /api/plans/...
router.use('/users', require('./users'));  // /api/users/...
router.use('/auth', require('./auth'));  // /api/auth/...
router.use('/contents', require('./contents'));  // /api/contents/...
// router.use('/comments', require('./comments'));  // /api/comments/...


module.exports = router;