const router = require('express').Router();

// router.use('/users', require('./users'));  // /api/users/...
router.use('/plans', require('./plans'));  // /api/plans/...
router.use('/members', require('./members'));  // /api/members/...

module.exports = router;